name: JIS Keymap SVG Conversion

on:
  workflow_dispatch:
  push:
    paths:
      - "keymap-drawer/roBa.svg"

jobs:
  convert-keymap-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Convert keymap SVG to JIS
        run: python keymap-drawer/convert_keymap_svg_to_jis.py

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Create GitHub Release
        run: |
          gh release create v1.0.0 \
            keymap-drawer/roBa.svg \
            --title "Release v1.0.0" \
            --notes "Automated release for JIS keymap SVG conversion." \
            --latest \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
